name: Push-to-LIVE-EC2

on:
  pull_request:
    branches:
      - live
  push:
    branches:
      - live
jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Create OANDA Config
        run: |          
          cat << EOF > config/oanda.cfg
          ${{ secrets.OANDA_CONFIG_LIVE }}
          EOF

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ vars.LIVE_REMOTE_HOST }}
          TARGET: ${{ vars.TARGET }}

